services:
  - type: web
    name: restaurant-menu
    env: node
    buildCommand: npm install && NODE_OPTIONS='--max-old-space-size=4096' npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: '--max-old-space-size=4096'
      - key: MONGODB_URI
        fromDatabase:
          name: restaurant-db
          property: connectionString